/**
 * Event keys copied from
 * anx-region-node_2/packages/modules/notifications/src/defaults.registry.ts
 * (`DEFAULT_NOTIFICATION_CATEGORIES`). Do not import that module.
 * When the registry gains a key, add it here and either map it in the catalog
 * or append it to `KNOWN_ROUTE_GAPS` on purpose.
 */
export const NOTIFICATION_EVENT_KEYS: readonly string[] = [
  'system.general.updated',
  'system.approvals.required',
  'system.critical.alert',
  'security.auth.approval.required',
  'security.auth.approval.denied',
  'security.oauth2_grant.inactivity_warning',
  'security.oauth2_grant.auto_disabled',
  'tasks.assigned',
  'tasks.unassigned',
  'tasks.status_changed',
  'tasks.completed',
  'tasks.reopened',
  'support.ticket.created',
  'support.ticket.assigned',
  'support.ticket.status_changed',
  'support.ticket.severity_escalated',
  'feedback.submission.responded',
  'feedback.submission.status_changed',
  'feedback.submission.merged',
  'feedback.submission.escalated',
  'feedback.submission.resolved',
  'crm.status_changed',
  'crm.stage_changed',
  'crm.assigned',
  'crm.activity.created',
  'crm.activity.completed',
  'crm.activity.rescheduled',
  'crm.task.created',
  'crm.task.assigned',
  'crm.task.status_changed',
  'finance.payment.pending_approval',
  'finance.payment.completed',
  'finance.payment.failed',
  'finance.accounting.proof_required',
  'finance.accounting.proof_extraction_failed',
  'finance.accounting.proof_submitted',
  'finance.accounting.proof_deadline_passed',
  'assets.lifecycle.state_changed',
  'assets.lifecycle.offline',
  'jobs.created',
  'jobs.assigned',
  'jobs.completed',
  'messages.inbox.received',
  'messages.mentions.received',
  'org.membership.applied',
  'org.membership.invited',
  'org.membership.joined',
  'org.membership.declined',
  'org.membership.invite_declined',
  'ai.approval.required',
  'ai.approval.approved',
  'ai.approval.denied',
  'ai.approval.cancelled',
  'compliance.aml.flagged',
];

/**
 * Registry keys that still resolve to `none` on the portal.
 * Asset and conversation keys are mapped to a section (portal detail is a follow-up).
 */
export const KNOWN_ROUTE_GAPS: readonly string[] = [
  'system.general.updated',
  'system.approvals.required',
  'system.critical.alert',
  'security.auth.approval.required',
  'security.auth.approval.denied',
  'security.oauth2_grant.inactivity_warning',
  'security.oauth2_grant.auto_disabled',
  'tasks.assigned',
  'tasks.unassigned',
  'tasks.status_changed',
  'tasks.completed',
  'tasks.reopened',
  'support.ticket.created',
  'support.ticket.assigned',
  'support.ticket.status_changed',
  'support.ticket.severity_escalated',
  'feedback.submission.responded',
  'feedback.submission.status_changed',
  'feedback.submission.merged',
  'feedback.submission.escalated',
  'feedback.submission.resolved',
  'finance.payment.pending_approval',
  'finance.payment.completed',
  'finance.payment.failed',
  'jobs.created',
  'jobs.assigned',
  'jobs.completed',
  'compliance.aml.flagged',
];

export const KNOWN_ROUTE_GAP_COUNT = KNOWN_ROUTE_GAPS.length;
